### ISSUE TITLE
error UNHANDLED EXCEPTION Error

### ISSUE THREAD

**Issue by mskian** [LekoArts/gatsby-starter-minimal-blog#58]
error UNHANDLED EXCEPTION Site Not Successfully Build
```bash
$ gatsby build
````
```
success open and validate gatsby-configs — 0.009 s
success load plugins — 0.320 s
success onPreInit — 0.095 s
success delete html and css files from previous builds — 0.006 s
success initialize cache — 0.010 s
success copy gatsby files — 0.021 s
success onPreBootstrap — 0.410 s
⠂ source and transform nodes
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3


WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

⠄ source and transform nodes
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3


WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3


WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3


WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3


WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3


WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

Generating image thumbnails [------------------------------] 5/548 2.9 secs 1%
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

success source and transform nodes — 7.122 s
success building schema — 1.217 s
success createPages — 0.246 s
success createPagesStatefully — 0.332 s
success onPreExtractQueries — 0.000 s
success update schema — 0.180 s
success extract queries from components — 0.218 s
success run graphql queries — 0.232 s — 19/19 82.36 queries/second
success write out page data — 0.008 s
success write out redirect data — 0.002 s
Generating image thumbnails [==============================] 548/548 36.3 secs 100%
success onPostBootstrap — 0.132 s

info bootstrap finished - 44.328 s

success Building production JavaScript and CSS bundles — 24.320 s
success Building static HTML for pages — 4.481 s — 16/16 14.14 pages/second
Generated public/sw.js, which will precache 11 files, totaling 1065074 bytes.
[ './node_modules/gatsby-mdx/loaders/mdx-wrappers.js\nModule build failed (from ./node_modules/gatsby-mdx/loaders/mdx-wrappers.js):\nTypeError: Cannot read property \'filter\' of undefined\n    at Object.module.exports (/home/groot/Santhosh/gatsby/hello-status/node_modules/gatsby-mdx/loaders/mdx-wrappers.js:21:6)\n @ ./node_modules/gatsby-mdx/utils/wrap-root-render-html-entry.js 8:0-62 10:36-44',
  'Error: Module build failed (from ./node_modules/gatsby-mdx/loaders/mdx-wrappers.js):\nTypeError: Cannot read property \'filter\' of undefined\n    at Object.module.exports (/home/groot/Santhosh/gatsby/hello-status/node_modules/gatsby-mdx/loaders/mdx-wrappers.js:21:6)\n    at Object../node_modules/gatsby-mdx/loaders/mdx-wrappers.js (evalmachine.<anonymous>:1781:7)\n    at __webpack_require__ (evalmachine.<anonymous>:20:30)\n    at Module../node_modules/gatsby-mdx/utils/wrap-root-render-html-entry.js (evalmachine.<anonymous>:1870:79)\n    at __webpack_require__ (evalmachine.<anonymous>:20:30)\n    at evalmachine.<anonymous>:84:18\n    at evalmachine.<anonymous>:87:10\n    at ContextifyScript.Script.runInContext (vm.js:59:29)\n    at ContextifyScript.Script.runInNewContext (vm.js:65:15)\n    at module.exports (/home/groot/Santhosh/gatsby/hello-status/node_modules/eval/eval.js:69:12)\n    at /home/groot/Santhosh/gatsby/hello-status/node_modules/static-site-generator-webpack-plugin/index.js:42:22' ]
error UNHANDLED EXCEPTION


  Error: no such file or directory
  
  - MemoryFileSystem.js:114 MemoryFileSystem.readFileSync
    [hello-status]/[memory-fs]/lib/MemoryFileSystem.js:114:10
  
  - render-html.js:56 compiler.run
    [hello-status]/[gatsby-mdx]/utils/render-html.js:56:26
  
  - Compiler.js:214 finalCallback
    [hello-status]/[webpack]/lib/Compiler.js:214:39
  
  - Compiler.js:263 hooks.done.callAsync.err
    [hello-status]/[webpack]/lib/Compiler.js:263:14
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [hello-status]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:261 emitRecords.err
    [hello-status]/[webpack]/lib/Compiler.js:261:22
  
  - Compiler.js:375 Compiler.emitRecords
    [hello-status]/[webpack]/lib/Compiler.js:375:39
  
  - Compiler.js:255 emitAssets.err
    [hello-status]/[webpack]/lib/Compiler.js:255:10
  
  - Compiler.js:361 hooks.afterEmit.callAsync.err
    [hello-status]/[webpack]/lib/Compiler.js:361:14
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [hello-status]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:358 asyncLib.forEach.err
    [hello-status]/[webpack]/lib/Compiler.js:358:27
  
  - async.js:2825 
    [hello-status]/[neo-async]/async.js:2825:7
  
  - async.js:2861 done
    [hello-status]/[neo-async]/async.js:2861:11
  
  - async.js:2813 
    [hello-status]/[neo-async]/async.js:2813:7
```

**Comment by LekoArts** [comment]
Sorry, can't help with that. Please open an issue on `gatsby-mdx`
